service: codepulse-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-tscpaths
  - serverless-offline

functions:
  prPulse:
    handler: ./src/handlers/prPulse.status


resources:
  - ${file(./config/resources/prPulse.bridge.yml)}