Resources:
  MyCustomEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(2 minutes)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - PrPulseLambdaFunction
              - Arn
          Id: "PrPulseTarget"

  PrPulseLambdaPermissionEvents:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: PrPulseLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - MyCustomEventBridgeRule
          - Arn

Outputs:
  EventBridgeRuleArn:
    Value:
      Ref: MyCustomEventBridgeRule
    Export:
      Name: EventBridgeRuleArn
